### ISSUE TITLE
Rate limiter possible problems

### ISSUE THREAD

**Issue by rkravchik** [gobwas/vk#1]
As I can see [here](https://github.com/gobwas/vk/blob/master/request.go#L174) and [here](https://github.com/gobwas/vk/blob/master/command/photo/photo.go#L140):
`it.limiter = syncutil.NewLimiter(time.Second, 3)`
you can meet extra time sleeping due to vk api behaviour described in this [issue](https://vk.com/bugs?act=show&id=5520927_19).

Maybe it's better to use common [throttle rater](https://github.com/golang/go/wiki/RateLimiting)?

**Comment by gobwas** [comment]
Hi! Thanks for the notice. I was trying to reproduce the issue you referred, and found that It is possible to get `Too many requests per second` with increased number of parallel requests. What is interesting, there are no errors if I use `rate.Limiter` (from [`rate`](https://godoc.org/golang.org/x/time/rate) package) with burst number equal to 3. 🤔 

Any way, I will switch to the `rate` package, thanks 🍻
